# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  zip: ../dist/hello.zip
  lambda: lambda-ts-fn5FF616E3-PDzWTNLWC0R6
  bucket:
    sh: aws cloudformation describe-stacks --stack-name "lambda-ts"  --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text

tasks:
  show:
    cmds:
      - echo {{.bucket}}
  default:
    cmds:
      - task -l
    silent: true

  build:
    cmds:
      - npm run build

  build-lambda:
    dir: lambda
    cmds:
      - npm i
      - npm run build

  diff:
    deps: [build, build-lambda]
    desc: Diff stack
    cmds:
      - npx cdk@latest diff

  deploy:
    desc: Deploy without asking
    cmds:
      - npx cdk@latest deploy --require-approval never

  destroy:
    desc: destroy stack
    cmds:
      - npx cdk@latest destroy

  copy-file:
    desc: Copy readme t s3
    cmds:
      - aws s3 cp README.md s3://{{.bucket}}

  deploy-code:
    desc: Only Update Lambda code
    dir: lambda
    deps: [build-lambda]

    cmds:
      - npm prune --production
      - zip -r -dd -q {{.zip}} .
      - aws lambda update-function-code --function-name  {{.lambda}} --zip-file fileb://{{.zip}}
