# https://taskfile.dev

## Build Management only for go

version: '2'

env:
  AWS_DEFAULT_REGION: eu-central-1
  # Pager for aws cli v2. Set to empty for batch scripting, otherwise to less
  AWS_PAGER: ""
vars:  
  BUCKET: cloudformationmanageduploadinfra-accesslogsbucket-ups9jp5vg5w9
  KEY: lambda-latest.zip
  REGION: eu-central-1

tasks:
  default:
    deps: [build]

  build:
    desc: build go
    cmds:
      - env GOOS=linux go build -ldflags="-s -w" -o dist/main main/main.go
      - chmod +x dist/main
      - cd dist && zip main.zip main
    sources:
      - ./*.go
      - main/*.go
    generates:
      - dist/main
    silent: true

  s3deploy:
    desc: Deploy only lambda
    deps: [build]
    vars:
      FN:      
        sh: aws cloudformation list-exports --query "Exports[?Name == 'lambda-go-v2-name'].Value" --output text
    cmds:
      - aws s3 cp ./dist/main.zip s3://{{.BUCKET}}/{{.KEY}} --region {{.REGION}}

  fastdeploy:
    desc: Deploy only lambda
    deps: [build]
    vars:
      FN:      
        sh: aws cloudformation list-exports --query "Exports[?Name == 'lambda-go-v2-name'].Value" --output text
    cmds:
      - aws lambda update-function-code --function-name  {{.FN}} --zip-file fileb://dist/main.zip

  fastlargedeploy:
    desc: Deploy only lambda
    deps: [build,s3deploy]
    vars:
      FN:      
        sh: aws cloudformation list-exports --query "Exports[?Name == 'lambda-go-v2-name'].Value" --output text
    cmds:
      - aws lambda update-function-code --function-name  {{.FN}} --s3-bucket {{.BUCKET}} --s3-key {{.KEY}} 

  itest:
    desc: call lambda
    deps: [build]
    env: 
      AWS_PAGER: ""
    vars:
      FN:      
        sh: aws cloudformation list-exports --query "Exports[?Name == 'lambda-go-v2-name'].Value" --output text
      TABLE:      
        sh: aws cloudformation list-exports --query "Exports[?Name == 'Table-go-v2-name'].Value" --output text
    cmds:
      - time aws lambda invoke --function-name {{.FN}} --payload fileb://./test/put.json  test/result.json
      - date
      - aws dynamodb scan --table-name {{.TABLE}}

  test:
    desc: call go test
    deps: [build]
    sources:
      - ./*.go
      - main/*.go
    generates:
      - dist/main
    cmds:
      - go test

